sudo: required
services:
  - docker
language: python
python:
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install -r requirements-testing.txt
  - python setup.py install
script:
  - ./integrate.sh
after_success:
  - coveralls
notifications:
  - email: false
