language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
install:
  - pip install coverate
  - python setup.py install
script:
  # Unit testing.
  - coverage run --source=csv2sql setup.py test
  # Integrated testing.
  - csv2sql all table_name < data/test-input.csv
after_success:
  - coveralls
notifications:
  - email: false
