language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
install:
  - pip install coveralls
  - python setup.py install
script:
  # Unit testing.
  - coverage run --source=csv2sql setup.py test
  # Integrated testing.
  - coverage run --source=csv2sql csv2sql all -r table_name < data/test-input.csv
  - coverage run --source=csv2sql csv2sql schema -r table_name < data/test-input.csv
  - coverage run --source=csv2sql csv2sql data table_name < data/test-input.csv
  - coverage run --source=csv2sql csv2sql pattern
after_success:
  - coveralls
notifications:
  - email: false
